# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- refs/tags/*

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c Release'

- task: PowerShell@1
  displayName: 'PowerShell Script'
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
  inputs:
    scriptType: inlineScript
    inlineScript: |
      Write-Host “Value of ReleaseFullPath: ‘“$env:BUILD_SOURCEBRANCH”’”
      $branch = $env:BUILD_SOURCEBRANCH
      $version = $branch.split(“/”)[2] 
      Write-Host (“##vso[task.setvariable variable=VERSION;isSecret=false;]$version”)

- task: replacetokens@3
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)'
    targetFiles: '**/NetSQS.nuspec'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: NuGetCommand@2
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
  inputs:
    command: 'pack'
    packagesToPack: '**/NetSQS/*.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'