# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c Release'

- task: PowerShell@1
  displayName: 'PowerShell Script'
  inputs:
    scriptType: inlineScript
    inlineScript: |
      Write-Host “Value of ReleaseFullPath: ‘“$env:BUILD_SOURCEBRANCH”’”
      $version = ""
      $branch = $env:BUILD_SOURCEBRANCH
      if ($branch.length -gt 0 -and $branch.IndexOf('tags') -gt -1) { 
        $version = $branch.split(“/”)[2] 
      } else {
        $version = '1.0.0'
      }
      Write-Host (“##vso[task.setvariable variable=VERSION;isSecret=false;]$version”)

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'xml'
    targetFiles: '**/NetSQS.nuspec'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/NetSQS/*.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'