apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sqs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqs
    spec:
      containers:
        - name: sqs
          image: roribio16/alpine-sqs:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 800Mi
          ports:
            - containerPort: 9324
---
apiVersion: v1
kind: Service
metadata:
  name: sqs
  labels:
    app: sqs
spec:
  ports:
   - port: 9324
  selector:
   app: sqs
  type: LoadBalancer